services:
  ai-tarot:
    image: wizerd/ai-tarot:latest
    container_name: ai-tarot
    restart: always
    ports:
      - 43222:8000
    environment:
      - api_key=<OPENAI 密钥>
      - api_base=<API BASE URL> # optional
      - model=gpt-4o # optional
      # - rate_limit=10/minute # optional
      # - user_rate_limit=600/hour # optional
      - github_client_id=xxx
      - github_client_secret=xxx
      - jwt_secret=secret
      - ad_client=ca-pub-xxx
      - ad_slot=123
